-- MySQL Script generated by MySQL Workbench
-- Tue May 11 17:13:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Internet_provider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Internet_provider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Internet_provider` DEFAULT CHARACTER SET utf8 ;
USE `Internet_provider` ;

-- -----------------------------------------------------
-- Table `Internet_provider`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internet_provider`.`status` (
  `id` tinyint unsigned not null AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internet_provider`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internet_provider`.`role` (
  `id` tinyint unsigned not null AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internet_provider`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internet_provider`.`user` (
  `id` bigint unsigned  not null AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `balance` DECIMAL NULL,
  `status_id` tinyint unsigned NOT NULL,
  `role_id` tinyint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `status_idx` (`status_id` ASC) VISIBLE,
  INDEX `role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `status`
    FOREIGN KEY (`status_id`)
    REFERENCES `Internet_provider`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role`
    FOREIGN KEY (`role_id`)
    REFERENCES `Internet_provider`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internet_provider`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internet_provider`.`service` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internet_provider`.`tariff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internet_provider`.`tariff` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` DECIMAL NOT NULL,
  `service_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`, `service_id`),
  INDEX `fk_tariff_service1_idx` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_tariff_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `Internet_provider`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internet_provider`.`included_package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internet_provider`.`included_package` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `subscription_date` DATETIME NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `service_id` bigint unsigned NOT NULL,
  `tariff_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `service_id`, `tariff_id`),
  INDEX `fk_included_service_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_included_service_service1_idx` (`service_id` ASC, `tariff_id` ASC) VISIBLE,
  INDEX `fk_included_service_tariff1_idx` (`tariff_id` ASC) VISIBLE,
  CONSTRAINT `fk_included_service_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Internet_provider`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_included_service_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `Internet_provider`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_included_service_tariff1`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `Internet_provider`.`tariff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internet_provider`.`included_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internet_provider`.`included_option` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `definition` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internet_provider`.`options_to_tariff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internet_provider`.`included_options_to_tariff` (
  `tariff_id` bigint unsigned NOT NULL,
  `included_option_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`tariff_id`, `included_option_id`),
  INDEX `fk_included_option_to_tariif_tariff1_idx` (`tariff_id` ASC) VISIBLE,
  INDEX `fk_included_option_to_tariif_included_option_idx` (`included_option_id` ASC) VISIBLE,
  CONSTRAINT `fk_included_option_to_tariif_tariff1`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `Internet_provider`.`tariff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_included_service_to_tariif_included_option1`
    FOREIGN KEY (`included_option_id`)
    REFERENCES `Internet_provider`.`included_option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


